In [1]:
import numpy as np

In [7]:
c = np.complex(2, 3)
c

(2+3j)

In [9]:
c.conjugate()

(2-3j)

In [10]:
a = np.arange(2, dtype=np.cdouble)

In [11]:
a

array([0.+0.j, 1.+0.j])

In [12]:
a[0] = 2+3j

In [13]:
a

array([2.+3.j, 1.+0.j])

In [23]:
z = np.array([1, 0])
z

array([1, 0])

In [24]:
pauli_z = np.array([[1, 0], [0, -1]])
pauli_z

array([[ 1,  0],
       [ 0, -1]])

In [25]:
pauli_z.dot(z)

array([1, 0])

In [27]:
from numpy import linalg as la

In [28]:
la.eig(pauli_z)

(array([ 1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

In [31]:
np.cos(np.pi/2)

6.123233995736766e-17

In [33]:
np.cos(np.pi) * 1

-1.0

In [34]:
np.exp(2+3j)

(-7.315110094901103+1.0427436562359045j)

In [35]:
np.exp(2)

7.38905609893065

In [41]:
np.exp(np.pi * 1j)

(-1+1.2246467991473532e-16j)

In [42]:
np.exp(np.pi / 2 * 1j)

(6.123233995736766e-17+1j)

In [43]:
np.exp(0j)

(1+0j)